In [1]:
import pandas as pd
import numpy as np

# Create the dataset from the markdown table
data = {
    'Brightness': [40, 50, 60, 10, 70, 60, 25],
    'Saturation': [20, 50, 90, 25, 70, 10, 80],
    'Class': ['Red', 'Blue', 'Blue', 'Red', 'Blue', 'Red', 'Blue']
}
df = pd.DataFrame(data)
display(df)

   Brightness  Saturation Class
0          40          20   Red
1          50          50  Blue
2          60          90  Blue
3          10          25   Red
4          70          70  Blue
5          60          10   Red
6          25          80  Blue

In [2]:
def euclidean_distance(point1, point2):
    """Calculates the Euclidean distance between two points."""
    # Ensure points are numpy arrays for element-wise operations
    point1 = np.array(point1)
    point2 = np.array(point2)
    return np.sqrt(np.sum((point1 - point2)**2))

In [3]:
# Define a new entry
new_entry = [45, 40] # Brightness, Saturation

# Calculate distances from the new entry to all existing data points
df['Distance'] = df.apply(lambda row: euclidean_distance(new_entry, [row['Brightness'], row['Saturation']]), axis=1)

display(df)

   Brightness  Saturation Class   Distance
0          40          20   Red  20.615528
1          50          50  Blue  11.180340
2          60          90  Blue  52.201533
3          10          25   Red  38.078866
4          70          70  Blue  39.051248
5          60          10   Red  33.541020
6          25          80  Blue  44.721360